from tkinter import colorchooser
import tkinter as tk
from PIL import Image, ImageTk, ImageColor
from rembg import remove
import webbrowser
from concurrent.futures import ThreadPoolExecutor
import threading
from queue import Queue, Empty
from tkinter import filedialog, colorchooser, messagebox, ttk
import io
import os
import base64
from io import BytesIO
import ctypes

icon_base64 = "AAABAAEAT08AAAEAIABgZQAAFgAAACgAAABPAAAAngAAAAEAIAAAAAAAhGEAAMMOAADDDgAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AADU9GYA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0ZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9CIA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT03QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAANT03QDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9LsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PSIANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAADU9HcA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT07gDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9O4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAA1PQRANT07gDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9JkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0ZgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAADU9JkA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PTuANT0EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAA1PQiANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9DMA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0mQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAADU9KoA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PTMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PSZANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9CIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAA1PREANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PQRANT07gDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9KoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAADU9MwA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PSZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0ZgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAA1PRmANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQA1PREANT0RADU9N0A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PTMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9N0A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0ZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PR3ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT03QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0EQDU9O4A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9HcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PSIANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9O4A1PQRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0IgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PSZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PSZANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0RADU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0mQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0uwDU9HcA1PR3ANT0dwDU9HcA1PR3ANT0dwDU9HcA1PR3ANT0dwDU9HcA1PR3ANT0dwDU9HcA1PSZANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0ZgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9N0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0iADU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9LsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PTdANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0EQDU9O4A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PRmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0dwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9KoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9GYA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PTdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9BEA1PTuANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PTMANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0dwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0iADU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9HcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PREANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT07gDU9BEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9CIA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PTdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0mQDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0mQDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0EQDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9EQA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9HcA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PSZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9CIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PTdANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9GYA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PSZAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PRVANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0uwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT03QDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT07gDU9BEAAAAAAAAAAAAAAAAAAAAAANT0qgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9FUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9HcA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PRmAAAAAAAAAAAAAAAAANT0IgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9N0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PQRANT07gDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0zAAAAAAAAAAAAAAAAADU9IgA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PRmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9HcA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PREAAAAAAAAAAAA1PTuANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PTuANT0EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PQiANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0mQAAAAAA1PRmANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0dwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9JkA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PQRANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9CIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PQzANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0qgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9JkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PQzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PRVANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU9N0A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PRmANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT03QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0EQDU9O4A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PR3ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9O4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0IgDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PSZANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0uwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9Lv///8A////AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0MwDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0mQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AADU9LsA1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PS7////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9CIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAA1PS7ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0/wDU9P8A1PT/ANT0u////wD///8A////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT0IgDU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AANT0MwDU9EQA1PREANT0RADU9EQA1PREANT0RADU9EQA1PREANT0RADU9DP///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAAAA////4AH/+ADgAAgA////4AH/+ADgAAgAf///4AP/+ADgAAgAf///wAP/+ADgAAwAP///wAP/+ADgAAwAP///gAf/+ADgAA4AP///gAf/+ADgAA4AH///AA//+ADgAA8AH///AA//+ADgAA8AAAAAAB//+ADgAA+AAAAAAB//+ADgAA+AAAAAAD//+ADgAA+AAAAAAD//+ADgAA/AAAAAAD//+ADgAA/AAAAAAH//+ADgAA/gAAAAAH//+ADgAA/gAAAAAP//+ADgAA/wAAAAAP//+ADgAA/wAf/wAf//+ADgAA/4AP/gAf//+ADgAA/4AP/gA///+ADgAA/4AH/gA///+ADgAA/8AH/AA///+ADgAA/8AH/AB///+ADgAA/+AD+AB///+ADgAA/+AD+AD///+ADgAA//AB+AD///+ADgAA//AB8AH///+ADgAA//gA8AH///+ADgAA//gA4AP///+ADgAA//gA4AP///+ADgAA//wAYAP///+ADgAA//wAQAf///+ADgAA//4AAAf///+ADgAA//4AAA////+ADgAA//8AAA////+ADgAA//8AAB////+ADgAA//+AAB////+ADgAA//+AAD////+ADgAA//+AAD////+ADgAA///AAH////+ADgAA///AAH////+ADgAA///gAH////+ADgAA///gAP////+ADgAA///wAP////+ADgAA///wAf////+ADgAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA/////////////gAA"

stop_processing = False
queue = Queue()

def start_processing():
    global stop_processing
    stop_processing = False

    input_file = file_entry.get()
    input_folder = folder_entry.get()
    output_folder = output_entry.get()
    bg_color = color_entry.get()

    if not output_folder:
        messagebox.showwarning("Cảnh báo", "Vui lòng chọn thư mục lưu.")
        return

    if input_file:
        processing_thread = threading.Thread(target=lambda: process_file(input_file, output_folder, bg_color))
        processing_thread.start()
    elif input_folder:
        processing_thread = threading.Thread(target=lambda: process_folder(input_folder, output_folder, bg_color))
        processing_thread.start()
    else:
        messagebox.showwarning("Cảnh báo", "Vui lòng chọn file ảnh hoặc thư mục ảnh để xử lý.")
def process_file(input_file, output_folder, bg_color):
    try:
        file_name = os.path.basename(input_file)
        output_file = os.path.join(output_folder, os.path.splitext(file_name)[0] + ".png")
        bg_color_rgb = ImageColor.getrgb(bg_color) if bg_color else None
        processed_img = remove_background(input_file, bg_color_rgb)

        if not bg_color_rgb:
            processed_img.save(output_file)
        else:
            processed_img = processed_img.convert('RGB') if processed_img.mode == 'RGBA' else processed_img
            processed_img.save(output_file)
        
        queue.put((5, input_file, output_file))
    except Exception as e:
        queue.put((0, f"Không thể xử lý file {input_file}. Lỗi: {e}"))

def process_folder(input_folder, output_folder, bg_color):
    global stop_processing
    files = [f for f in os.listdir(input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    total_files = len(files)
    
    if total_files == 0:
        messagebox.showwarning("Thông báo", "Không có tệp hình ảnh nào trong thư mục đã chọn.")
        return

    progress_bar['maximum'] = total_files
    processed_files = 0

    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = [executor.submit(process_and_save_file, f, input_folder, output_folder, bg_color) for f in files]

        for i, future in enumerate(futures):
            if stop_processing:
                queue.put((2, "Quá trình đã dừng."))
                break
            
            future.result()
            processed_files += 1
            
            queue.put((3, processed_files, total_files))
    
    if not stop_processing:
        queue.put((4, "Tất cả các file trong thư mục đã được xử lý."))

def process_and_save_file(file_name, input_folder, output_folder, bg_color):
    input_file = os.path.join(input_folder, file_name)
    process_file(input_file, output_folder, bg_color)

def remove_background(input_path, bg_color=None):
    with open(input_path, "rb") as input_file:
        input_data = input_file.read()
        result = remove(input_data, alpha_matting=True, alpha_matting_foreground_threshold=240, alpha_matting_background_threshold=10)
        img = Image.open(io.BytesIO(result))

        if bg_color:
            background = Image.new('RGBA', img.size, bg_color)
            img = Image.alpha_composite(background, img)

        return img

def select_file():
    file_path = filedialog.askopenfilename(filetypes=[("Image Files", "*.png;*.jpg;*.jpeg")])
    if file_path:
        show_image(file_path, label_before)
        file_entry.delete(0, tk.END)
        file_entry.insert(0, file_path)

def select_folder(entry):
    folder_path = filedialog.askdirectory()
    if folder_path:
        entry.delete(0, tk.END)
        entry.insert(0, folder_path)

def select_color():
    color = colorchooser.askcolor()[1]
    if color:
        color_entry.delete(0, tk.END)
        color_entry.insert(0, color)

def show_image(image_path, label):
    img = Image.open(image_path)
    base_width = 200
    w_percent = (base_width / float(img.size[0]))
    h_size = int((float(img.size[1]) * float(w_percent)))
    img = img.resize((base_width, h_size), Image.Resampling.LANCZOS)
    
    img_tk = ImageTk.PhotoImage(img)
    label.config(image=img_tk, bg='white')
    label.image = img_tk

def stop_process():
    global stop_processing
    stop_processing = True
def update_gui():
    try:
        while True:
            message_type, *message = queue.get_nowait()

            if message_type == 1:  # Success message
                messagebox.showinfo("Thành công", message[0])
            elif message_type == 0:  # Error message
                messagebox.showerror("Lỗi", message[0])
            elif message_type == 2:  # Process stopped
                messagebox.showinfo("Dừng", message[0])
            elif message_type == 3:  # Progress update
                processed_files, total_files = message
                progress_bar['value'] = processed_files
                progress_label.config(text=f"Đã xử lý {processed_files}/{total_files} files")
            elif message_type == 4:  # Folder processing complete
                messagebox.showinfo("Thành công", message[0])
            elif message_type == 5:  # Cập nhật hình ảnh trước và sau khi xử lý
                input_file, output_file = message
                show_image(input_file, label_before)  # Hiển thị hình ảnh trước khi xử lý
                show_image(output_file, label_after)  # Hiển thị hình ảnh sau khi xử lý
            
            root.update_idletasks()

    except Empty:  # Sử dụng ngoại lệ Empty
        pass
    
    root.after(100, update_gui)
root = tk.Tk()
root.title("XOÁ NỀN AI |TỐNG GIANG |ZALO 0378.180.567")
root.geometry("960x700")
root.configure(bg='white')
root.resizable(False, False)

icon_data = base64.b64decode(icon_base64)
icon_image = Image.open(BytesIO(icon_data))
icon = ImageTk.PhotoImage(icon_image)

root.iconphoto(True, icon)

tk.Label(root, text="THƯ MỤC CẦN XOÁ NỀN", font=('Arial', 12), bg='green', fg='white').place(x=20, y=20, width=200, height=30)
folder_entry = tk.Entry(root, width=50, bg='lightgreen')
folder_entry.place(x=230, y=20, width=500, height=30)
tk.Button(root, text="CHỌN THƯ MỤC", command=lambda: select_folder(folder_entry), font=('Arial', 12), bg='red', fg='white').place(x=740, y=20, width=150, height=30)

tk.Label(root, text="THƯ MỤC LƯU", font=('Arial', 12), bg='green', fg='white').place(x=20, y=70, width=200, height=30)
output_entry = tk.Entry(root, width=50, bg='lightgreen')
output_entry.place(x=230, y=70, width=500, height=30)
tk.Button(root, text="CHỌN THƯ MỤC", command=lambda: select_folder(output_entry), font=('Arial', 12), bg='red', fg='white').place(x=740, y=70, width=150, height=30)

tk.Button(root, text="CHẠY 1 ẢNH TẢI LÊN", command=select_file, font=('Arial', 12), bg='green', fg='white').place(x=20, y=120, width=200, height=30)
file_entry = tk.Entry(root, width=50, bg='lightgreen')
file_entry.place(x=230, y=120, width=500, height=30)

tk.Label(root, text="CHỌN MÀU NỀN", font=('Arial', 12), bg='green', fg='white').place(x=20, y=170, width=200, height=30)
color_entry = tk.Entry(root, width=20, bg='lightgreen')
color_entry.place(x=230, y=170, width=100, height=30)
tk.Button(root, text="CHỌN", command=select_color, font=('Arial', 12), bg='green', fg='white').place(x=340, y=170, width=80, height=30)

tk.Label(root, text="TRƯỚC", font=('Arial', 14), fg='brown').place(x=150, y=220)
tk.Label(root, text="SAU", font=('Arial', 14), fg='brown').place(x=650, y=220)

label_before = tk.Label(root, bg='#f0f0f0', bd=2, relief='sunken')
label_before.place(x=100, y=250, width=200)

label_after = tk.Label(root, bg='#f0f0f0', bd=2, relief='sunken')
label_after.place(x=550, y=250, width=200)

progress_bar = ttk.Progressbar(root, orient="horizontal", length=500, mode="determinate")
progress_bar.place(x=230, y=560)

progress_label = tk.Label(root, text="", font=('Arial', 10), bg='white', fg='black')
progress_label.place(x=230, y=590)

tk.Button(root, text="CHẠY", command=start_processing, font=('Arial', 14), bg='green', fg='white').place(x=300, y=620, width=150, height=50)
tk.Button(root, text="DỪNG", command=stop_process, font=('Arial', 14), bg='brown', fg='white').place(x=510, y=620, width=150, height=50)

author_label = tk.Label(root, text="BẢN QUYỀN: TỐNG GIANG", font=('Arial', 7), fg='black', cursor="hand2")
author_label.place(x=800, y=670)
author_label.bind("<Button-1>", lambda e: open_facebook())

def open_facebook():
    webbrowser.open("https://www.facebook.com/profile.php?id=100057170550808")

root.after(100, update_gui)

root.mainloop()
